---
- name: >-
    Allow the {{ bot_user }} user to run sudo /usr/bin/systemctl restart {{ service_name }}
  community.general.sudoers:
    name: macunaima-service
    user: "{{ bot_user }}"
    commands:
      - /usr/bin/systemctl restart {{ service_name }}
      - /usr/bin/systemctl stop {{ service_name }}
      - /usr/bin/systemctl start {{ service_name }}

- name: Copiar a unit do systemd
  ansible.builtin.template:
    src: macunaima.service.j2
    dest: /etc/systemd/system/macunaima.service
    mode: '0644'
    force: true

- name: Habilitar e iniciar a unit do systemd
  ansible.builtin.systemd_service:
    name: macunaima.service
    state: started
    enabled: true
    daemon_reload: true
