---
- name: Copiar a unit do systemd
  ansible.builtin.template:
    src: macunaima.service.j2
    dest: /etc/systemd/system/macunaima.service
    mode: '0644'
    force: true


- name: Habilitar e iniciar a unit do systemd
  ansible.builtin.systemd_service:
    name: macunaima.service
    state: started
    enabled: true
    daemon_reload: true
